# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltminion',
            name='status',
            field=models.CharField(choices=[('add', '已经认证'), ('wait', '未认证'), ('del', '删除认证')], max_length=64, verbose_name='认证状态'),
        ),
    ]
