# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20160717_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltminion',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='MinionIP'),
        ),
    ]
