# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20160718_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saltminion',
            name='ip',
        ),
    ]
