# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20160801_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='firmware',
        ),
        migrations.AddField(
            model_name='server',
            name='kernel',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='内核'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='contacts_phone',
            field=models.IntegerField(verbose_name='联系人电话'),
        ),
    ]
