# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20160804_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='kernel',
            new_name='kernelrelease',
        ),
    ]
