# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Moudle', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='moudle',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='属于'),
        ),
    ]
