# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='manufactory',
        ),
    ]
