# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_ram_manufactory'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='bandwidth',
            field=models.CharField(default=200, max_length=63, verbose_name='机房带宽'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idc',
            name='contacts_phone',
            field=models.IntegerField(default=17710909539, verbose_name='技术电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idc',
            name='contacts_qq',
            field=models.IntegerField(default=22102107, verbose_name='机房技术QQ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idc',
            name='contacts',
            field=models.CharField(max_length=63, verbose_name='机房技术'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_phone',
            field=models.IntegerField(verbose_name='机房电话'),
        ),
    ]
