# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20160804_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='manufactory',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='model',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='sn',
        ),
    ]
