# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20160805_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='manufactory',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='制造商'),
        ),
        migrations.AddField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='磁盘型号'),
        ),
        migrations.AddField(
            model_name='disk',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号'),
        ),
    ]
