# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20160716_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltminion',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已经认证'), (2, '未认证'), (3, '删除认证')], max_length=64, verbose_name='认证状态'),
        ),
    ]
